package com.example.api

import com.example.BuildConfig
import com.squareup.moshi.JsonClass
import okhttp3.OkHttpClient
import okhttp3.MediaType.Companion.toMediaType
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit
import android.util.Log
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.delay

@JsonClass(generateAdapter = true)
data class Part(val text: String? = null)

@JsonClass(generateAdapter = true)
data class Content(val parts: List<Part>)

@JsonClass(generateAdapter = true)
data class GenerateContentRequest(
    val contents: List<Content>,
    val systemInstruction: Content? = null
)

@JsonClass(generateAdapter = true)
data class Candidate(val content: Content)

@JsonClass(generateAdapter = true)
data class GenerateContentResponse(val candidates: List<Candidate>?)

interface GeminiApiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GenerateContentRequest
    ): GenerateContentResponse
}

object GeminiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"
    private val mutex = Mutex()
    private var lastCallTime = 0L

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(MoshiConverterFactory.create())
        .build()

    val service: GeminiApiService = retrofit.create(GeminiApiService::class.java)

    /**
     * Executes a prompt and returns the text response or a descriptive error message.
     */
    suspend fun generateText(prompt: String, systemInstruction: String? = null): String {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return "API Key is missing. Please add your GEMINI_API_KEY in the Secrets panel in AI Studio."
        }
        
        return mutex.withLock {
            val now = System.currentTimeMillis()
            val timeSinceLastCall = now - lastCallTime
            if (timeSinceLastCall < 2000) {
                delay(2000 - timeSinceLastCall)
            }
            
            var result: String? = null
            var lastException: Exception? = null
            var currentDelay = 1500L
            
            for (attempt in 1..3) {
                try {
                    val request = GenerateContentRequest(
                        contents = listOf(Content(parts = listOf(Part(text = prompt)))),
                        systemInstruction = systemInstruction?.let { Content(parts = listOf(Part(text = it))) }
                    )
                    val response = service.generateContent(apiKey, request)
                    val responseText = response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text
                    if (responseText != null) {
                        result = responseText
                        break
                    } else {
                        throw Exception("No recommendation generated by AI.")
                    }
                } catch (e: Exception) {
                    lastException = e
                    Log.e("GeminiClient", "Attempt $attempt failed: ${e.message}", e)
                    
                    val isRateLimit = e is retrofit2.HttpException && e.code() == 429
                    val isConnectionOrRate = isRateLimit || e.message?.contains("429") == true || e.message?.contains("limit") == true
                    
                    if (isConnectionOrRate && attempt < 3) {
                        delay(currentDelay)
                        currentDelay *= 2
                    } else {
                        break
                    }
                }
            }
            
            lastCallTime = System.currentTimeMillis()
            
            if (result != null) {
                result
            } else {
                val errMsg = lastException?.localizedMessage ?: "Failed to reach AI Server"
                if (errMsg.contains("429")) {
                    "Error: AI Coach is currently busy guiding other rescued users. Please retry in a few seconds."
                } else {
                    "Error: $errMsg"
                }
            }
        }
    }
}
